import { Meter } from '@/components/ui/Meter'
import { cn } from '@/lib/utils'
import type { Insight } from '@/types'

const toneText = {
  info: 'text-ink',
  ok: 'text-ok-ink',
  warn: 'text-warn-ink',
  danger: 'text-danger-ink',
} as const

const toneMeter = {
  info: 'brand',
  ok: 'ok',
  warn: 'warn',
  danger: 'danger',
} as const

/**
 * Small derived observations about the student's own week.
 *
 * Everything here comes straight from records the student generated by
 * attending classes and filing requests — no inferred behaviour and no
 * profiling. If a figure cannot be derived from the dataset, it is not shown.
 *
 * A figure that is a proportion gets a meter under it, because a bar is read
 * faster than "3 of 5". A figure that is not — an amount of money, a number of
 * days — gets nothing, since a bar there would be decoration pretending to be
 * data. That asymmetry is deliberate and is decided upstream in `buildInsights`.
 */
export function InsightRow({ insights, className }: { insights: Insight[]; className?: string }) {
  if (insights.length === 0) return null

  return (
    <dl
      className={cn(
        'grid grid-cols-2 gap-px overflow-hidden rounded-card border border-line bg-line sm:grid-cols-3 lg:grid-cols-6',
        className,
      )}
    >
      {insights.map((insight) => {
        const tone = insight.tone ?? 'info'
        return (
          <div key={insight.label} className="flex flex-col bg-surface px-4 py-3.5">
            <dt className="truncate text-[11.5px] text-ink-subtle">{insight.label}</dt>
            <dd
              className={cn(
                'mt-1.5 truncate text-[19px] font-semibold leading-none tracking-tight tabular-nums',
                toneText[tone],
              )}
            >
              {insight.value}
            </dd>

            {insight.detail ? (
              <p className="mt-1.5 truncate text-[11px] text-ink-subtle">{insight.detail}</p>
            ) : null}

            {insight.progress !== undefined ? (
              <Meter
                value={insight.progress}
                tone={toneMeter[tone]}
                size="sm"
                label={`${insight.label}: ${insight.value}`}
                className="mt-auto pt-3"
              />
            ) : null}
          </div>
        )
      })}
    </dl>
  )
}
