import { cn } from '@/lib/utils'
import type { Insight } from '@/types'

const toneText = {
  info: 'text-ink',
  ok: 'text-ok-ink',
  warn: 'text-warn-ink',
  danger: 'text-danger-ink',
} as const

/**
 * Small derived observations about the student's own week.
 *
 * Everything here comes straight from records the student generated by
 * attending classes and filing requests — no inferred behaviour and no
 * profiling. If a figure cannot be derived from the dataset, it is not shown.
 */
export function InsightRow({ insights, className }: { insights: Insight[]; className?: string }) {
  if (insights.length === 0) return null

  return (
    <dl
      className={cn(
        'grid grid-cols-2 gap-px overflow-hidden rounded-card border border-line bg-line sm:grid-cols-3 lg:grid-cols-5',
        className,
      )}
    >
      {insights.map((insight) => (
        <div key={insight.label} className="bg-surface px-4 py-3.5">
          <dt className="text-[11.5px] text-ink-subtle">{insight.label}</dt>
          <dd
            className={cn(
              'mt-1 truncate text-[15px] font-semibold tracking-tight',
              toneText[insight.tone ?? 'info'],
            )}
          >
            {insight.value}
          </dd>
          {insight.detail ? (
            <p className="mt-0.5 truncate text-[11px] text-ink-subtle">{insight.detail}</p>
          ) : null}
        </div>
      ))}
    </dl>
  )
}
